export const userFieldCatalog = [
  {
    key: 'userId',
    label: 'ID de usuario',
    type: 'string',
    required: true,
    notes: 'Identificador único interno.',
  },
  {
    key: 'tenantId',
    label: 'ID de studio',
    type: 'string',
    required: true,
    notes: 'Separación de datos por negocio.',
  },
  {
    key: 'firstName',
    label: 'Nombre',
    type: 'string',
    required: true,
    notes: 'Sin apodos para evitar duplicidad.',
  },
  {
    key: 'lastName',
    label: 'Apellidos',
    type: 'string',
    required: true,
    notes: 'Para búsquedas y trazabilidad legal.',
  },
  {
    key: 'phoneE164',
    label: 'Teléfono',
    type: 'string',
    required: true,
    notes: 'Formato internacional +52...',
  },
  {
    key: 'email',
    label: 'Correo',
    type: 'string',
    required: false,
    notes: 'Opcional, útil para reportes y recovery.',
  },
  {
    key: 'birthDate',
    label: 'Fecha de nacimiento',
    type: 'string',
    required: false,
    notes: 'Formato YYYY-MM-DD.',
  },
  {
    key: 'disciplineIds',
    label: 'Disciplinas',
    type: 'array<string>',
    required: true,
    notes: 'Una o más disciplinas activas.',
  },
  {
    key: 'status',
    label: 'Estado',
    type: 'enum',
    required: true,
    notes: 'active | inactive | blocked.',
  },
  {
    key: 'createdAtCustom',
    label: 'Creado en',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
  {
    key: 'updatedAtCustom',
    label: 'Actualizado en',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
]

export const rewardFieldCatalog = [
  {
    key: 'rewardId',
    label: 'ID de premio',
    type: 'string',
    required: true,
    notes: 'Identificador técnico único.',
  },
  {
    key: 'name',
    label: 'Nombre del premio',
    type: 'string',
    required: true,
    notes: 'Nombre comercial visible en dashboard.',
  },
  {
    key: 'description',
    label: 'Descripción',
    type: 'string',
    required: false,
    notes: 'Texto explicativo del beneficio.',
  },
  {
    key: 'requiredVisits',
    label: 'Visitas requeridas',
    type: 'number',
    required: true,
    notes: 'Umbral para habilitar canje.',
  },
  {
    key: 'stockType',
    label: 'Tipo de inventario',
    type: 'enum',
    required: true,
    notes: 'finite | infinite.',
  },
  {
    key: 'stockAvailable',
    label: 'Stock disponible',
    type: 'number',
    required: true,
    notes: 'Solo aplica para finite.',
  },
  {
    key: 'maxPerUser',
    label: 'Máximo por usuario',
    type: 'number',
    required: true,
    notes: 'Límite total por usuario.',
  },
  {
    key: 'status',
    label: 'Estado',
    type: 'enum',
    required: true,
    notes: 'active | paused | archived.',
  },
  {
    key: 'validFromCustom',
    label: 'Vigencia inicio',
    type: 'string',
    required: true,
    notes: 'Timestamp custom local.',
  },
  {
    key: 'validUntilCustom',
    label: 'Vigencia fin',
    type: 'string',
    required: true,
    notes: 'Timestamp custom local.',
  },
  {
    key: 'createdAtCustom',
    label: 'Creado en',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
  {
    key: 'updatedAtCustom',
    label: 'Actualizado en',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
]

export const qrFieldCatalog = [
  {
    key: 'qrCodeId',
    label: 'ID de QR',
    type: 'string',
    required: true,
    notes: 'Clave única por campaña/qr.',
  },
  {
    key: 'name',
    label: 'Nombre interno',
    type: 'string',
    required: true,
    notes: 'Ej. Ballet Matutino.',
  },
  {
    key: 'disciplineId',
    label: 'Disciplina',
    type: 'string',
    required: true,
    notes: 'Disciplina a la que acredita.',
  },
  {
    key: 'branchId',
    label: 'Sucursal',
    type: 'string',
    required: true,
    notes: 'Sede donde aplica el escaneo.',
  },
  {
    key: 'status',
    label: 'Estado',
    type: 'enum',
    required: true,
    notes: 'active | paused | archived.',
  },
  {
    key: 'validFromCustom',
    label: 'Vigencia inicio',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
  {
    key: 'validUntilCustom',
    label: 'Vigencia fin',
    type: 'string',
    required: true,
    notes: 'Timestamp custom con dayjs.',
  },
]

